// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:motoparts_manager/models/maintenance_record.dart';
import 'package:motoparts_manager/models/motorcycle.dart';
import 'package:motoparts_manager/models/part.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MaintenanceRecordAdapter());
    registerAdapter(MotoPartAdapter());
    registerAdapter(MotorcycleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MaintenanceRecordAdapter());
    registerAdapter(MotoPartAdapter());
    registerAdapter(MotorcycleAdapter());
  }
}
